<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductAddSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([

            [
                'name' => 'Debug Product 108',
                'slug' => 'debug-product-108',
                'short_description' => 'Debug product for error fix',
                'description' => 'Debug product for error fix',
                'regular_price' => 10,
                'sale_price' => null,
                'SKU' => 'DEBUG-108',
                'stock_status' => 'instock',
                'featured' => false,
                'quantity' => 1,
                'thumbnail' => null,
                'images' => null,
                'category_id' => 1,
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],
            [
                'name' => 'Tulipan Negro Coco Pure White Huile de Corps',
                'slug' => 'tulipan-negro-coco-pure-white-huile-de-corps',
                'short_description' => 'Tulipan Negro Coco Pure White Huile de Corps',
                'description' => 'Tulipan Negro Coco Pure White Huile de Corps',
                'regular_price' => 35.0,
                'sale_price' => null,
                'SKU' => 'TN-1-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Coco_Pure_White_Huile_de_Corps_1.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro – Huile de Corps « Fresa & Nata »',
                'slug' => 'tulipan-negro-huile-de-corps-fresa-nata',
                'short_description' => 'Tulipan Negro – Huile de Corps « Fresa & Nata »',
                'description' => 'Tulipan Negro – Huile de Corps « Fresa & Nata »',
                'regular_price' => 35.0,
                'sale_price' => null,
                'SKU' => 'TN-2-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_–_Huile_de_Corps_«_Fresa_&_Nata_»_2.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro – Huile de Corps Rosa',
                'slug' => 'tulipan-negro-huile-de-corps-rosa',
                'short_description' => 'Tulipan Negro – Huile de Corps Rosa',
                'description' => 'Tulipan Negro – Huile de Corps Rosa',
                'regular_price' => 35.0,
                'sale_price' => null,
                'SKU' => 'TN-3-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_–_Huile_de_Corps_Rosa_3.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Candy Fantasy Huile de Corps',
                'slug' => 'tulipan-negro-candy-fantasy-huile-de-corps',
                'short_description' => 'Tulipan Negro Candy Fantasy Huile de Corps',
                'description' => 'Tulipan Negro Candy Fantasy Huile de Corps',
                'regular_price' => 35.0,
                'sale_price' => null,
                'SKU' => 'TN-4-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Candy_Fantasy_Huile_de_Corps_4.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Shampoing Tulipan Negro anti-frisottis Low Poo sans sulfate 500 ml',
                'slug' => 'shampoing-tulipan-negro-anti-frisottis-low-poo-sans-sulfate-500-ml',
                'short_description' => 'Shampoing Tulipan Negro anti-frisottis Low Poo sans sulfate 500 ml',
                'description' => 'Shampoing Tulipan Negro anti-frisottis Low Poo sans sulfate 500 ml',
                'regular_price' => 100.0,
                'sale_price' => null,
                'SKU' => 'TN-5-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Shampoing_Tulipan_Negro_anti-frisottis_Low_Poo_sans_sulfate_500_ml_5.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Shampoing sans sulfate Tulipan Negro Low Poo Soin Doux 500 ml',
                'slug' => 'shampoing-sans-sulfate-tulipan-negro-low-poo-soin-doux-500-ml',
                'short_description' => 'Shampoing sans sulfate Tulipan Negro Low Poo Soin Doux 500 ml',
                'description' => 'Shampoing sans sulfate Tulipan Negro Low Poo Soin Doux 500 ml',
                'regular_price' => 100.0,
                'sale_price' => null,
                'SKU' => 'TN-6-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Shampoing_sans_sulfate_Tulipan_Negro_Low_Poo_Soin_Doux_500_ml_6.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Shampoing sans sulfate Low Poo pour cheveux teints 500 ml',
                'slug' => 'tulipan-negro-shampoing-sans-sulfate-low-poo-pour-cheveux-teints-500-ml',
                'short_description' => 'Tulipan Negro Shampoing sans sulfate Low Poo pour cheveux teints 500 ml',
                'description' => 'Tulipan Negro Shampoing sans sulfate Low Poo pour cheveux teints 500 ml',
                'regular_price' => 100.0,
                'sale_price' => null,
                'SKU' => 'TN-7-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Shampoing_sans_sulfate_Low_Poo_pour_cheveux_teints_500_ml_7.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Shampoing réparateur intensif Tulipan Negro Low Poo sans sulfate 500 ml',
                'slug' => 'shampoing-r-parateur-intensif-tulipan-negro-low-poo-sans-sulfate-500-ml',
                'short_description' => 'Shampoing réparateur intensif Tulipan Negro Low Poo sans sulfate 500 ml',
                'description' => 'Shampoing réparateur intensif Tulipan Negro Low Poo sans sulfate 500 ml',
                'regular_price' => 100.0,
                'sale_price' => null,
                'SKU' => 'TN-8-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Shampoing_réparateur_intensif_Tulipan_Negro_Low_Poo_sans_sulfate_500_ml_8.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Masque Capillaire Répare et Protège 400 ml',
                'slug' => 'masque-capillaire-r-pare-et-prot-ge-400-ml',
                'short_description' => 'Masque Capillaire Répare et Protège 400 ml',
                'description' => 'Masque Capillaire Répare et Protège 400 ml',
                'regular_price' => 45.0,
                'sale_price' => null,
                'SKU' => 'TN-9-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Masque_Capillaire_Répare_et_Protège_400_ml_9.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Masque Capillaire Hydratant intensif 400 ml',
                'slug' => 'masque-capillaire-hydratant-intensif-400-ml',
                'short_description' => 'Masque Capillaire Hydratant intensif 400 ml',
                'description' => 'Masque Capillaire Hydratant intensif 400 ml',
                'regular_price' => 45.0,
                'sale_price' => null,
                'SKU' => 'TN-10-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Masque_Capillaire_Hydratant_intensif_400_ml_10.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Masque Capillaire Doux et Lisse 400 ml',
                'slug' => 'masque-capillaire-doux-et-lisse-400-ml',
                'short_description' => 'Masque Capillaire Doux et Lisse 400 ml',
                'description' => 'Masque Capillaire Doux et Lisse 400 ml',
                'regular_price' => 45.0,
                'sale_price' => null,
                'SKU' => 'TN-11-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Masque_Capillaire_Doux_et_Lisse_400_ml_11.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Shampoing Micellaire Revitalisant & Fortifiant Tulipan Negro',
                'slug' => 'shampoing-micellaire-revitalisant-fortifiant-tulipan-negro',
                'short_description' => 'Shampoing Micellaire Revitalisant & Fortifiant Tulipan Negro',
                'description' => 'Shampoing Micellaire Revitalisant & Fortifiant Tulipan Negro',
                'regular_price' => 33.0,
                'sale_price' => null,
                'SKU' => 'TN-12-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Shampoing_Micellaire_Revitalisant_&_Fortifiant_Tulipan_Negro_12.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Shampoing MicellaireTulipan Negro à Haut Volume',
                'slug' => 'shampoing-micellairetulipan-negro-haut-volume',
                'short_description' => 'Shampoing MicellaireTulipan Negro à Haut Volume',
                'description' => 'Shampoing MicellaireTulipan Negro à Haut Volume',
                'regular_price' => 33.0,
                'sale_price' => null,
                'SKU' => 'TN-13-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Shampoing_MicellaireTulipan_Negro_à_Haut_Volume_13.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Masque Capillaire Sublimateur de Couleur 400 ml',
                'slug' => 'masque-capillaire-sublimateur-de-couleur-400-ml',
                'short_description' => 'Masque Capillaire Sublimateur de Couleur 400 ml',
                'description' => 'Masque Capillaire Sublimateur de Couleur 400 ml',
                'regular_price' => 45.0,
                'sale_price' => null,
                'SKU' => 'TN-14-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Masque_Capillaire_Sublimateur_de_Couleur_400_ml_14.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Shampoing Micellaire Purifiant Tulipan Negro',
                'slug' => 'shampoing-micellaire-purifiant-tulipan-negro',
                'short_description' => 'Shampoing Micellaire Purifiant Tulipan Negro',
                'description' => 'Shampoing Micellaire Purifiant Tulipan Negro',
                'regular_price' => 33.0,
                'sale_price' => null,
                'SKU' => 'TN-15-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Shampoing_Micellaire_Purifiant_Tulipan_Negro_15.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Shampoing Micellaire Restructurant de Couleur Tulipan Negro',
                'slug' => 'shampoing-micellaire-restructurant-de-couleur-tulipan-negro',
                'short_description' => 'Shampoing Micellaire Restructurant de Couleur Tulipan Negro',
                'description' => 'Shampoing Micellaire Restructurant de Couleur Tulipan Negro',
                'regular_price' => 33.0,
                'sale_price' => null,
                'SKU' => 'TN-16-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Shampoing_Micellaire_Restructurant_de_Couleur_Tulipan_Negro_16.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Actoner Bain de Bouche Anti-Taches 500 ml',
                'slug' => 'actoner-bain-de-bouche-anti-taches-500-ml',
                'short_description' => 'Actoner Bain de Bouche Anti-Taches 500 ml',
                'description' => 'Actoner Bain de Bouche Anti-Taches 500 ml',
                'regular_price' => 37.0,
                'sale_price' => null,
                'SKU' => 'TN-17-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Actoner_Bain_de_Bouche_Anti-Taches_500_ml_17.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Actoner ZERO Bain de Bouche Anti-Taches 500 ml',
                'slug' => 'actoner-zero-bain-de-bouche-anti-taches-500-ml',
                'short_description' => 'Actoner ZERO Bain de Bouche Anti-Taches 500 ml',
                'description' => 'Actoner ZERO Bain de Bouche Anti-Taches 500 ml',
                'regular_price' => 37.0,
                'sale_price' => null,
                'SKU' => 'TN-18-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Actoner_ZERO_Bain_de_Bouche_Anti-Taches_500_ml_18.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Actoner Bain de Bouche Complet 7 en 1 500 ml',
                'slug' => 'actoner-bain-de-bouche-complet-7-en-1-500-ml',
                'short_description' => 'Actoner Bain de Bouche Complet 7 en 1 500 ml',
                'description' => 'Actoner Bain de Bouche Complet 7 en 1 500 ml',
                'regular_price' => 37.0,
                'sale_price' => null,
                'SKU' => 'TN-19-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Actoner_Bain_de_Bouche_Complet_7_en_1_500_ml_19.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Actoner Alia Bain de Bouche 500 ml',
                'slug' => 'actoner-alia-bain-de-bouche-500-ml',
                'short_description' => 'Actoner Alia Bain de Bouche 500 ml',
                'description' => 'Actoner Alia Bain de Bouche 500 ml',
                'regular_price' => 37.0,
                'sale_price' => null,
                'SKU' => 'TN-20-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Actoner_Alia_Bain_de_Bouche_500_ml_20.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Actoner ZERO Bain de Bouche Complete Care 500 ml',
                'slug' => 'actoner-zero-bain-de-bouche-complete-care-500-ml',
                'short_description' => 'Actoner ZERO Bain de Bouche Complete Care 500 ml',
                'description' => 'Actoner ZERO Bain de Bouche Complete Care 500 ml',
                'regular_price' => 37.0,
                'sale_price' => null,
                'SKU' => 'TN-21-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Actoner_ZERO_Bain_de_Bouche_Complete_Care_500_ml_21.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Actoner Bain de Bouche Explosion Menthe 500 ml',
                'slug' => 'actoner-bain-de-bouche-explosion-menthe-500-ml',
                'short_description' => 'Actoner Bain de Bouche Explosion Menthe 500 ml',
                'description' => 'Actoner Bain de Bouche Explosion Menthe 500 ml',
                'regular_price' => 37.0,
                'sale_price' => null,
                'SKU' => 'TN-22-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Actoner_Bain_de_Bouche_Explosion_Menthe_500_ml_22.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Actoner ZERO Bain de Bouche Gencives Sensibles 500 ml',
                'slug' => 'actoner-zero-bain-de-bouche-gencives-sensibles-500-ml',
                'short_description' => 'Actoner ZERO Bain de Bouche Gencives Sensibles 500 ml',
                'description' => 'Actoner ZERO Bain de Bouche Gencives Sensibles 500 ml',
                'regular_price' => 37.0,
                'sale_price' => null,
                'SKU' => 'TN-23-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Actoner_ZERO_Bain_de_Bouche_Gencives_Sensibles_500_ml_23.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Actoner ZERO Bain de Bouche Menthe 500 ml',
                'slug' => 'actoner-zero-bain-de-bouche-menthe-500-ml',
                'short_description' => 'Actoner ZERO Bain de Bouche Menthe 500 ml',
                'description' => 'Actoner ZERO Bain de Bouche Menthe 500 ml',
                'regular_price' => 37.0,
                'sale_price' => null,
                'SKU' => 'TN-24-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Actoner_ZERO_Bain_de_Bouche_Menthe_500_ml_24.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Actoner Bain de Bouche Arctique 500 ml',
                'slug' => 'actoner-bain-de-bouche-arctique-500-ml',
                'short_description' => 'Actoner Bain de Bouche Arctique 500 ml',
                'description' => 'Actoner Bain de Bouche Arctique 500 ml',
                'regular_price' => 37.0,
                'sale_price' => null,
                'SKU' => 'TN-25-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Actoner_Bain_de_Bouche_Arctique_500_ml_25.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Eau de Cologne Tulipan Negro Fraise et Crème 800 ml',
                'slug' => 'eau-de-cologne-tulipan-negro-fraise-et-cr-me-800-ml',
                'short_description' => 'Eau de Cologne Tulipan Negro Fraise et Crème 800 ml',
                'description' => 'Eau de Cologne Tulipan Negro Fraise et Crème 800 ml',
                'regular_price' => 36.0,
                'sale_price' => null,
                'SKU' => 'TN-26-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Eau_de_Cologne_Tulipan_Negro_Fraise_et_Crème_800_ml_26.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Fraiche Tulipan Negro Cologne Eau de Cologne 800 ml',
                'slug' => 'fraiche-tulipan-negro-cologne-eau-de-cologne-800-ml',
                'short_description' => 'Fraiche Tulipan Negro Cologne Eau de Cologne 800 ml',
                'description' => 'Fraiche Tulipan Negro Cologne Eau de Cologne 800 ml',
                'regular_price' => 36.0,
                'sale_price' => null,
                'SKU' => 'TN-27-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Fraiche_Tulipan_Negro_Cologne_Eau_de_Cologne_800_ml_27.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Eau de Cologne originale Tulipan Negro Cologne 800 ml',
                'slug' => 'eau-de-cologne-originale-tulipan-negro-cologne-800-ml',
                'short_description' => 'Eau de Cologne originale Tulipan Negro Cologne 800 ml',
                'description' => 'Eau de Cologne originale Tulipan Negro Cologne 800 ml',
                'regular_price' => 36.0,
                'sale_price' => null,
                'SKU' => 'TN-28-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Eau_de_Cologne_originale_Tulipan_Negro_Cologne_800_ml_28.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Eau de Cologne Citrus Green 800 ml',
                'slug' => 'tulipan-negro-eau-de-cologne-citrus-green-800-ml',
                'short_description' => 'Tulipan Negro Eau de Cologne Citrus Green 800 ml',
                'description' => 'Tulipan Negro Eau de Cologne Citrus Green 800 ml',
                'regular_price' => 36.0,
                'sale_price' => null,
                'SKU' => 'TN-29-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Eau_de_Cologne_Citrus_Green_800_ml_29.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Miguel Palacio colonia 800 ml',
                'slug' => 'miguel-palacio-colonia-800-ml',
                'short_description' => 'Miguel Palacio colonia 800 ml',
                'description' => 'Miguel Palacio colonia 800 ml',
                'regular_price' => 36.0,
                'sale_price' => null,
                'SKU' => 'TN-30-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Miguel_Palacio_colonia_800_ml_30.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Eau de Cologne Tulipan Negro Fraise et Crème 50 ml',
                'slug' => 'eau-de-cologne-tulipan-negro-fraise-et-cr-me-50-ml',
                'short_description' => 'Eau de Cologne Tulipan Negro Fraise et Crème 50 ml',
                'description' => 'Eau de Cologne Tulipan Negro Fraise et Crème 50 ml',
                'regular_price' => 48.0,
                'sale_price' => null,
                'SKU' => 'TN-31-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Eau_de_Cologne_Tulipan_Negro_Fraise_et_Crème_50_ml_31.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Briseis Feu d’Amour Cologne 1000 ml',
                'slug' => 'briseis-feu-d-amour-cologne-1000-ml',
                'short_description' => 'Briseis Feu d’Amour Cologne 1000 ml',
                'description' => 'Briseis Feu d’Amour Cologne 1000 ml',
                'regular_price' => 85.0,
                'sale_price' => null,
                'SKU' => 'TN-32-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Briseis_Feu_d’Amour_Cologne_1000_ml_32.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Farina Argent Eau de Cologne 600 ml',
                'slug' => 'tulipan-negro-farina-argent-eau-de-cologne-600-ml',
                'short_description' => 'Tulipan Negro Farina Argent Eau de Cologne 600 ml',
                'description' => 'Tulipan Negro Farina Argent Eau de Cologne 600 ml',
                'regular_price' => 40.0,
                'sale_price' => null,
                'SKU' => 'TN-33-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Farina_Argent_Eau_de_Cologne_600_ml_33.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Briseis Revuelo Cologne 1000 ml',
                'slug' => 'briseis-revuelo-cologne-1000-ml',
                'short_description' => 'Briseis Revuelo Cologne 1000 ml',
                'description' => 'Briseis Revuelo Cologne 1000 ml',
                'regular_price' => 85.0,
                'sale_price' => null,
                'SKU' => 'TN-34-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Briseis_Revuelo_Cologne_1000_ml_34.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Cologne Florale Lilas Tulipan Negro d’Italie 500 ml',
                'slug' => 'cologne-florale-lilas-tulipan-negro-d-italie-500-ml',
                'short_description' => 'Cologne Florale Lilas Tulipan Negro d’Italie 500 ml',
                'description' => 'Cologne Florale Lilas Tulipan Negro d’Italie 500 ml',
                'regular_price' => 96.0,
                'sale_price' => null,
                'SKU' => 'TN-35-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Cologne_Florale_Lilas_Tulipan_Negro_d’Italie_500_ml_35.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Briseis Pour Homme Cologne 1000 ml',
                'slug' => 'briseis-pour-homme-cologne-1000-ml',
                'short_description' => 'Briseis Pour Homme Cologne 1000 ml',
                'description' => 'Briseis Pour Homme Cologne 1000 ml',
                'regular_price' => 85.0,
                'sale_price' => null,
                'SKU' => 'TN-36-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Briseis_Pour_Homme_Cologne_1000_ml_36.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Cologne Florale Tulipan Negro Jasmin d’Egypte 500 ml',
                'slug' => 'cologne-florale-tulipan-negro-jasmin-d-egypte-500-ml',
                'short_description' => 'Cologne Florale Tulipan Negro Jasmin d’Egypte 500 ml',
                'description' => 'Cologne Florale Tulipan Negro Jasmin d’Egypte 500 ml',
                'regular_price' => 96.0,
                'sale_price' => null,
                'SKU' => 'TN-37-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Cologne_Florale_Tulipan_Negro_Jasmin_d’Egypte_500_ml_37.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Eau de Cologne Tulipan Negro Mandarine & Citron Vert 800 ml',
                'slug' => 'eau-de-cologne-tulipan-negro-mandarine-citron-vert-800-ml',
                'short_description' => 'Eau de Cologne Tulipan Negro Mandarine & Citron Vert 800 ml',
                'description' => 'Eau de Cologne Tulipan Negro Mandarine & Citron Vert 800 ml',
                'regular_price' => 36.0,
                'sale_price' => null,
                'SKU' => 'TN-38-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Eau_de_Cologne_Tulipan_Negro_Mandarine_&_Citron_Vert_800_ml_38.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Cologne Florale Tulipan Negro Oriental Rose 500 ml',
                'slug' => 'cologne-florale-tulipan-negro-oriental-rose-500-ml',
                'short_description' => 'Cologne Florale Tulipan Negro Oriental Rose 500 ml',
                'description' => 'Cologne Florale Tulipan Negro Oriental Rose 500 ml',
                'regular_price' => 96.0,
                'sale_price' => null,
                'SKU' => 'TN-39-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Cologne_Florale_Tulipan_Negro_Oriental_Rose_500_ml_39.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Riviera Violet Tulipan Negro Floral Cologne 500 ml',
                'slug' => 'riviera-violet-tulipan-negro-floral-cologne-500-ml',
                'short_description' => 'Riviera Violet Tulipan Negro Floral Cologne 500 ml',
                'description' => 'Riviera Violet Tulipan Negro Floral Cologne 500 ml',
                'regular_price' => 96.0,
                'sale_price' => null,
                'SKU' => 'TN-40-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Riviera_Violet_Tulipan_Negro_Floral_Cologne_500_ml_40.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipán Negro Coco Eau de Cologne Pure White 50 ml',
                'slug' => 'tulip-n-negro-coco-eau-de-cologne-pure-white-50-ml',
                'short_description' => 'Tulipán Negro Coco Eau de Cologne Pure White 50 ml',
                'description' => 'Tulipán Negro Coco Eau de Cologne Pure White 50 ml',
                'regular_price' => 48.0,
                'sale_price' => null,
                'SKU' => 'TN-41-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipán_Negro_Coco_Eau_de_Cologne_Pure_White_50_ml_41.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Eau de Cologne Douce Violette 50 ml',
                'slug' => 'tulipan-negro-eau-de-cologne-douce-violette-50-ml',
                'short_description' => 'Tulipan Negro Eau de Cologne Douce Violette 50 ml',
                'description' => 'Tulipan Negro Eau de Cologne Douce Violette 50 ml',
                'regular_price' => 48.0,
                'sale_price' => null,
                'SKU' => 'TN-42-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Eau_de_Cologne_Douce_Violette_50_ml_42.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Candy Fantasy Tulipan Negro Eau de Cologne 50 ml',
                'slug' => 'candy-fantasy-tulipan-negro-eau-de-cologne-50-ml',
                'short_description' => 'Candy Fantasy Tulipan Negro Eau de Cologne 50 ml',
                'description' => 'Candy Fantasy Tulipan Negro Eau de Cologne 50 ml',
                'regular_price' => 48.0,
                'sale_price' => null,
                'SKU' => 'TN-43-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Candy_Fantasy_Tulipan_Negro_Eau_de_Cologne_50_ml_43.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Eau de Cologne Tulipan Negro Cotton Cloud 50 ml',
                'slug' => 'eau-de-cologne-tulipan-negro-cotton-cloud-50-ml',
                'short_description' => 'Eau de Cologne Tulipan Negro Cotton Cloud 50 ml',
                'description' => 'Eau de Cologne Tulipan Negro Cotton Cloud 50 ml',
                'regular_price' => 48.0,
                'sale_price' => null,
                'SKU' => 'TN-44-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Eau_de_Cologne_Tulipan_Negro_Cotton_Cloud_50_ml_44.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Eau de Cologne Tulipan Negro Passion Fraise et Cerise 50 ml',
                'slug' => 'eau-de-cologne-tulipan-negro-passion-fraise-et-cerise-50-ml',
                'short_description' => 'Eau de Cologne Tulipan Negro Passion Fraise et Cerise 50 ml',
                'description' => 'Eau de Cologne Tulipan Negro Passion Fraise et Cerise 50 ml',
                'regular_price' => 48.0,
                'sale_price' => null,
                'SKU' => 'TN-45-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Eau_de_Cologne_Tulipan_Negro_Passion_Fraise_et_Cerise_50_ml_45.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Lait Corporel Beurre de Karité & Huile de Coco 400 ml',
                'slug' => 'lait-corporel-beurre-de-karit-huile-de-coco-400-ml',
                'short_description' => 'Lait Corporel Beurre de Karité & Huile de Coco 400 ml',
                'description' => 'Lait Corporel Beurre de Karité & Huile de Coco 400 ml',
                'regular_price' => 35.0,
                'sale_price' => null,
                'SKU' => 'TN-46-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Lait_Corporel_Beurre_de_Karité_&_Huile_de_Coco_400_ml_46.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Lait Corporel Black Tulip Fraise et Crème 400 ml',
                'slug' => 'lait-corporel-black-tulip-fraise-et-cr-me-400-ml',
                'short_description' => 'Lait Corporel Black Tulip Fraise et Crème 400 ml',
                'description' => 'Lait Corporel Black Tulip Fraise et Crème 400 ml',
                'regular_price' => 35.0,
                'sale_price' => null,
                'SKU' => 'TN-47-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Lait_Corporel_Black_Tulip_Fraise_et_Crème_400_ml_47.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Candy Fantasy Lait Pour Le Corps Tulipe Noire 400 ml',
                'slug' => 'candy-fantasy-lait-pour-le-corps-tulipe-noire-400-ml',
                'short_description' => 'Candy Fantasy Lait Pour Le Corps Tulipe Noire 400 ml',
                'description' => 'Candy Fantasy Lait Pour Le Corps Tulipe Noire 400 ml',
                'regular_price' => 35.0,
                'sale_price' => null,
                'SKU' => 'TN-48-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Candy_Fantasy_Lait_Pour_Le_Corps_Tulipe_Noire_400_ml_48.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Lait Corporel Elixir d’Argan & Huile d’Amande 400 ml Tulipan Negro',
                'slug' => 'lait-corporel-elixir-d-argan-huile-d-amande-400-ml-tulipan-negro',
                'short_description' => 'Lait Corporel Elixir d’Argan & Huile d’Amande 400 ml Tulipan Negro',
                'description' => 'Lait Corporel Elixir d’Argan & Huile d’Amande 400 ml Tulipan Negro',
                'regular_price' => 35.0,
                'sale_price' => null,
                'SKU' => 'TN-49-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Lait_Corporel_Elixir_d’Argan_&_Huile_d’Amande_400_ml_Tulipan_Negro_49.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Lait Corporel Aloe Vera, Coton & Rose Musquée 400 ml',
                'slug' => 'lait-corporel-aloe-vera-coton-rose-musqu-e-400-ml',
                'short_description' => 'Lait Corporel Aloe Vera, Coton & Rose Musquée 400 ml',
                'description' => 'Lait Corporel Aloe Vera, Coton & Rose Musquée 400 ml',
                'regular_price' => 35.0,
                'sale_price' => null,
                'SKU' => 'TN-50-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Lait_Corporel_Aloe_Vera,_Coton_&_Rose_Musquée_400_ml_50.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Lait Corporel Huile d’Olive Méditerranéenne 400 ml',
                'slug' => 'lait-corporel-huile-d-olive-m-diterran-enne-400-ml',
                'short_description' => 'Lait Corporel Huile d’Olive Méditerranéenne 400 ml',
                'description' => 'Lait Corporel Huile d’Olive Méditerranéenne 400 ml',
                'regular_price' => 35.0,
                'sale_price' => null,
                'SKU' => 'TN-51-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Lait_Corporel_Huile_d’Olive_Méditerranéenne_400_ml_51.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Déodorant Déo Spray Coton et Talc 200 ml',
                'slug' => 'tulipan-negro-d-odorant-d-o-spray-coton-et-talc-200-ml',
                'short_description' => 'Tulipan Negro Déodorant Déo Spray Coton et Talc 200 ml',
                'description' => 'Tulipan Negro Déodorant Déo Spray Coton et Talc 200 ml',
                'regular_price' => 28.0,
                'sale_price' => null,
                'SKU' => 'TN-52-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Déodorant_Déo_Spray_Coton_et_Talc_200_ml_52.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Déodorant Tulipan Negro Roll sur Coton et Talc 50 ml',
                'slug' => 'd-odorant-tulipan-negro-roll-sur-coton-et-talc-50-ml',
                'short_description' => 'Déodorant Tulipan Negro Roll sur Coton et Talc 50 ml',
                'description' => 'Déodorant Tulipan Negro Roll sur Coton et Talc 50 ml',
                'regular_price' => 20.0,
                'sale_price' => null,
                'SKU' => 'TN-53-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Déodorant_Tulipan_Negro_Roll_sur_Coton_et_Talc_50_ml_53.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Déodorant Spray Pour Homme Sport 200 ml',
                'slug' => 'tulipan-negro-d-odorant-spray-pour-homme-sport-200-ml',
                'short_description' => 'Tulipan Negro Déodorant Spray Pour Homme Sport 200 ml',
                'description' => 'Tulipan Negro Déodorant Spray Pour Homme Sport 200 ml',
                'regular_price' => 28.0,
                'sale_price' => null,
                'SKU' => 'TN-54-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Déodorant_Spray_Pour_Homme_Sport_200_ml_54.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Déodorant Tulipan Negro Deo Stick Candy Fantasy 60 ml',
                'slug' => 'd-odorant-tulipan-negro-deo-stick-candy-fantasy-60-ml',
                'short_description' => 'Déodorant Tulipan Negro Deo Stick Candy Fantasy 60 ml',
                'description' => 'Déodorant Tulipan Negro Deo Stick Candy Fantasy 60 ml',
                'regular_price' => 27.0,
                'sale_price' => null,
                'SKU' => 'TN-55-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Déodorant_Tulipan_Negro_Deo_Stick_Candy_Fantasy_60_ml_55.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Déodorant Stick Pour Homme Sport 75 ml',
                'slug' => 'tulipan-negro-d-odorant-stick-pour-homme-sport-75-ml',
                'short_description' => 'Tulipan Negro Déodorant Stick Pour Homme Sport 75 ml',
                'description' => 'Tulipan Negro Déodorant Stick Pour Homme Sport 75 ml',
                'regular_price' => 35.0,
                'sale_price' => null,
                'SKU' => 'TN-56-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Déodorant_Stick_Pour_Homme_Sport_75_ml_56.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Déodorant Tulipan negro Deo Stick Datta Sport 75 ml',
                'slug' => 'd-odorant-tulipan-negro-deo-stick-datta-sport-75-ml',
                'short_description' => 'Déodorant Tulipan negro Deo Stick Datta Sport 75 ml',
                'description' => 'Déodorant Tulipan negro Deo Stick Datta Sport 75 ml',
                'regular_price' => 28.0,
                'sale_price' => null,
                'SKU' => 'TN-57-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Déodorant_Tulipan_negro_Deo_Stick_Datta_Sport_75_ml_57.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan negro Déodorant Deo Stick Cotton Cloud 60 ml',
                'slug' => 'tulipan-negro-d-odorant-deo-stick-cotton-cloud-60-ml',
                'short_description' => 'Tulipan negro Déodorant Deo Stick Cotton Cloud 60 ml',
                'description' => 'Tulipan negro Déodorant Deo Stick Cotton Cloud 60 ml',
                'regular_price' => 27.0,
                'sale_price' => null,
                'SKU' => 'TN-58-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_negro_Déodorant_Deo_Stick_Cotton_Cloud_60_ml_58.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Déodorant Tulipan Negro Deo Stick Datta Space 75 ml',
                'slug' => 'd-odorant-tulipan-negro-deo-stick-datta-space-75-ml',
                'short_description' => 'Déodorant Tulipan Negro Deo Stick Datta Space 75 ml',
                'description' => 'Déodorant Tulipan Negro Deo Stick Datta Space 75 ml',
                'regular_price' => 28.0,
                'sale_price' => null,
                'SKU' => 'TN-59-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Déodorant_Tulipan_Negro_Deo_Stick_Datta_Space_75_ml_59.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Déodorant Déo Spray Savon Crème 200 ml',
                'slug' => 'tulipan-negro-d-odorant-d-o-spray-savon-cr-me-200-ml',
                'short_description' => 'Tulipan Negro Déodorant Déo Spray Savon Crème 200 ml',
                'description' => 'Tulipan Negro Déodorant Déo Spray Savon Crème 200 ml',
                'regular_price' => 28.0,
                'sale_price' => null,
                'SKU' => 'TN-60-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Déodorant_Déo_Spray_Savon_Crème_200_ml_60.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Déodorant Fraise et Crème Déodorant Spray 200 ml',
                'slug' => 'tulipan-negro-d-odorant-fraise-et-cr-me-d-odorant-spray-200-ml',
                'short_description' => 'Tulipan Negro Déodorant Fraise et Crème Déodorant Spray 200 ml',
                'description' => 'Tulipan Negro Déodorant Fraise et Crème Déodorant Spray 200 ml',
                'regular_price' => 28.0,
                'sale_price' => null,
                'SKU' => 'TN-61-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Déodorant_Fraise_et_Crème_Déodorant_Spray_200_ml_61.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Déodorant Roll on Original 50 ml',
                'slug' => 'tulipan-negro-d-odorant-roll-on-original-50-ml',
                'short_description' => 'Tulipan Negro Déodorant Roll on Original 50 ml',
                'description' => 'Tulipan Negro Déodorant Roll on Original 50 ml',
                'regular_price' => 20.0,
                'sale_price' => null,
                'SKU' => 'TN-62-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Déodorant_Roll_on_Original_50_ml_62.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Antisudorifique Roll-On Coco Pure White 50 ml',
                'slug' => 'antisudorifique-roll-on-coco-pure-white-50-ml',
                'short_description' => 'Antisudorifique Roll-On Coco Pure White 50 ml',
                'description' => 'Antisudorifique Roll-On Coco Pure White 50 ml',
                'regular_price' => 20.0,
                'sale_price' => null,
                'SKU' => 'TN-63-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Antisudorifique_Roll-On_Coco_Pure_White_50_ml_63.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Déodorant Tulipan Negro Déodorant Spray Candy Fantasy 200 ml',
                'slug' => 'd-odorant-tulipan-negro-d-odorant-spray-candy-fantasy-200-ml',
                'short_description' => 'Déodorant Tulipan Negro Déodorant Spray Candy Fantasy 200 ml',
                'description' => 'Déodorant Tulipan Negro Déodorant Spray Candy Fantasy 200 ml',
                'regular_price' => 28.0,
                'sale_price' => null,
                'SKU' => 'TN-64-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Déodorant_Tulipan_Negro_Déodorant_Spray_Candy_Fantasy_200_ml_64.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Déodorant Deo Stick Kiss Fraise et Crème 60 ml',
                'slug' => 'tulipan-negro-d-odorant-deo-stick-kiss-fraise-et-cr-me-60-ml',
                'short_description' => 'Tulipan Negro Déodorant Deo Stick Kiss Fraise et Crème 60 ml',
                'description' => 'Tulipan Negro Déodorant Deo Stick Kiss Fraise et Crème 60 ml',
                'regular_price' => 27.0,
                'sale_price' => null,
                'SKU' => 'TN-65-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Déodorant_Deo_Stick_Kiss_Fraise_et_Crème_60_ml_65.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Déaodorant Tulipan Negro Deo Stick Coco Pure White 60 ml',
                'slug' => 'd-aodorant-tulipan-negro-deo-stick-coco-pure-white-60-ml',
                'short_description' => 'Déaodorant Tulipan Negro Deo Stick Coco Pure White 60 ml',
                'description' => 'Déaodorant Tulipan Negro Deo Stick Coco Pure White 60 ml',
                'regular_price' => 27.0,
                'sale_price' => null,
                'SKU' => 'TN-66-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Déaodorant_Tulipan_Negro_Deo_Stick_Coco_Pure_White_60_ml_66.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Antisudorifique Roll-on Fraise & Crème 50 ml',
                'slug' => 'antisudorifique-roll-on-fraise-cr-me-50-ml',
                'short_description' => 'Antisudorifique Roll-on Fraise & Crème 50 ml',
                'description' => 'Antisudorifique Roll-on Fraise & Crème 50 ml',
                'regular_price' => 20.0,
                'sale_price' => null,
                'SKU' => 'TN-67-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Antisudorifique_Roll-on_Fraise_&_Crème_50_ml_67.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Déodorant Deo Stick Sweet Violet 60 ml',
                'slug' => 'tulipan-negro-d-odorant-deo-stick-sweet-violet-60-ml',
                'short_description' => 'Tulipan Negro Déodorant Deo Stick Sweet Violet 60 ml',
                'description' => 'Tulipan Negro Déodorant Deo Stick Sweet Violet 60 ml',
                'regular_price' => 27.0,
                'sale_price' => null,
                'SKU' => 'TN-68-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Déodorant_Deo_Stick_Sweet_Violet_60_ml_68.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Deo Stick Déodorant Passion Fraise et Cerise 60 ml',
                'slug' => 'tulipan-negro-deo-stick-d-odorant-passion-fraise-et-cerise-60-ml',
                'short_description' => 'Tulipan Negro Deo Stick Déodorant Passion Fraise et Cerise 60 ml',
                'description' => 'Tulipan Negro Deo Stick Déodorant Passion Fraise et Cerise 60 ml',
                'regular_price' => 27.0,
                'sale_price' => null,
                'SKU' => 'TN-69-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Deo_Stick_Déodorant_Passion_Fraise_et_Cerise_60_ml_69.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Déodorant Spray Original 200 ml',
                'slug' => 'tulipan-negro-d-odorant-spray-original-200-ml',
                'short_description' => 'Tulipan Negro Déodorant Spray Original 200 ml',
                'description' => 'Tulipan Negro Déodorant Spray Original 200 ml',
                'regular_price' => 28.0,
                'sale_price' => null,
                'SKU' => 'TN-70-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Déodorant_Spray_Original_200_ml_70.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Déodorant Tulipan Negro Déo Roll à l’Aloe Vera et au Jojoba 50 ml',
                'slug' => 'd-odorant-tulipan-negro-d-o-roll-l-aloe-vera-et-au-jojoba-50-ml',
                'short_description' => 'Déodorant Tulipan Negro Déo Roll à l’Aloe Vera et au Jojoba 50 ml',
                'description' => 'Déodorant Tulipan Negro Déo Roll à l’Aloe Vera et au Jojoba 50 ml',
                'regular_price' => 20.0,
                'sale_price' => null,
                'SKU' => 'TN-71-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Déodorant_Tulipan_Negro_Déo_Roll_à_l’Aloe_Vera_et_au_Jojoba_50_ml_71.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel Tulipán Negro Fresa y Nata 650 ml',
                'slug' => 'gel-tulip-n-negro-fresa-y-nata-650-ml',
                'short_description' => 'Gel Tulipán Negro Fresa y Nata 650 ml',
                'description' => 'Gel Tulipán Negro Fresa y Nata 650 ml',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-72-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_Tulipán_Negro_Fresa_y_Nata_650_ml_72.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Tulipan Negro Gel de Bain au Ginseng Noir 650 ml',
                'slug' => 'tulipan-negro-gel-de-bain-au-ginseng-noir-650-ml',
                'short_description' => 'Tulipan Negro Gel de Bain au Ginseng Noir 650 ml',
                'description' => 'Tulipan Negro Gel de Bain au Ginseng Noir 650 ml',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-73-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Tulipan_Negro_Gel_de_Bain_au_Ginseng_Noir_650_ml_73.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de bain Coco Pure Blanc 650 ml Tulipan Negro',
                'slug' => 'gel-de-bain-coco-pure-blanc-650-ml-tulipan-negro',
                'short_description' => 'Gel de bain Coco Pure Blanc 650 ml Tulipan Negro',
                'description' => 'Gel de bain Coco Pure Blanc 650 ml Tulipan Negro',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-74-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_bain_Coco_Pure_Blanc_650_ml_Tulipan_Negro_74.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de bain au coton et au talc Tulipan Negro 650 ml',
                'slug' => 'gel-de-bain-au-coton-et-au-talc-tulipan-negro-650-ml',
                'short_description' => 'Gel de bain au coton et au talc Tulipan Negro 650 ml',
                'description' => 'Gel de bain au coton et au talc Tulipan Negro 650 ml',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-75-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_bain_au_coton_et_au_talc_Tulipan_Negro_650_ml_75.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de bain crème au savon tulipan negro 650 ml',
                'slug' => 'gel-de-bain-cr-me-au-savon-tulipan-negro-650-ml',
                'short_description' => 'Gel de bain crème au savon tulipan negro 650 ml',
                'description' => 'Gel de bain crème au savon tulipan negro 650 ml',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-76-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_bain_crème_au_savon_tulipan_negro_650_ml_76.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de bain Tulipan Negro Douce Violette 650 ml',
                'slug' => 'gel-de-bain-tulipan-negro-douce-violette-650-ml',
                'short_description' => 'Gel de bain Tulipan Negro Douce Violette 650 ml',
                'description' => 'Gel de bain Tulipan Negro Douce Violette 650 ml',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-77-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_bain_Tulipan_Negro_Douce_Violette_650_ml_77.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de Bain Yaourt aux Fruits Rouges 650 ML',
                'slug' => 'gel-de-bain-yaourt-aux-fruits-rouges-650-ml',
                'short_description' => 'Gel de Bain Yaourt aux Fruits Rouges 650 ML',
                'description' => 'Gel de Bain Yaourt aux Fruits Rouges 650 ML',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-78-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_Bain_Yaourt_aux_Fruits_Rouges_650_ML_78.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de bain Licorne Guimauve 650 ML',
                'slug' => 'gel-de-bain-licorne-guimauve-650-ml',
                'short_description' => 'Gel de bain Licorne Guimauve 650 ML',
                'description' => 'Gel de bain Licorne Guimauve 650 ML',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-79-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_bain_Licorne_Guimauve_650_ML_79.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Candy Fantasy Gel De Bain Tulipan Negro 650 ml',
                'slug' => 'candy-fantasy-gel-de-bain-tulipan-negro-650-ml',
                'short_description' => 'Candy Fantasy Gel De Bain Tulipan Negro 650 ml',
                'description' => 'Candy Fantasy Gel De Bain Tulipan Negro 650 ml',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-80-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Candy_Fantasy_Gel_De_Bain_Tulipan_Negro_650_ml_80.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de bain Tulipan Negro Caramel & Toffee 650 ml',
                'slug' => 'gel-de-bain-tulipan-negro-caramel-toffee-650-ml',
                'short_description' => 'Gel de bain Tulipan Negro Caramel & Toffee 650 ml',
                'description' => 'Gel de bain Tulipan Negro Caramel & Toffee 650 ml',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-81-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_bain_Tulipan_Negro_Caramel_&_Toffee_650_ml_81.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de bain Tulipan Negro Bisous Fraise 650 ML',
                'slug' => 'gel-de-bain-tulipan-negro-bisous-fraise-650-ml',
                'short_description' => 'Gel de bain Tulipan Negro Bisous Fraise 650 ML',
                'description' => 'Gel de bain Tulipan Negro Bisous Fraise 650 ML',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-82-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_bain_Tulipan_Negro_Bisous_Fraise_650_ML_82.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de bain Tulipan Negro Ozone Protect 650 ml',
                'slug' => 'gel-de-bain-tulipan-negro-ozone-protect-650-ml',
                'short_description' => 'Gel de bain Tulipan Negro Ozone Protect 650 ml',
                'description' => 'Gel de bain Tulipan Negro Ozone Protect 650 ml',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-83-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_bain_Tulipan_Negro_Ozone_Protect_650_ml_83.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de Bain Tulipan Negro Chocolat Noir Praliné 650 ml',
                'slug' => 'gel-de-bain-tulipan-negro-chocolat-noir-pralin-650-ml',
                'short_description' => 'Gel de Bain Tulipan Negro Chocolat Noir Praliné 650 ml',
                'description' => 'Gel de Bain Tulipan Negro Chocolat Noir Praliné 650 ml',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-84-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_Bain_Tulipan_Negro_Chocolat_Noir_Praliné_650_ml_84.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de bain nuage de coton Tulipan Negro 650 ml',
                'slug' => 'gel-de-bain-nuage-de-coton-tulipan-negro-650-ml',
                'short_description' => 'Gel de bain nuage de coton Tulipan Negro 650 ml',
                'description' => 'Gel de bain nuage de coton Tulipan Negro 650 ml',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-85-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_bain_nuage_de_coton_Tulipan_Negro_650_ml_85.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Secret Bath Gold Dream Gel de bain tulipan Negro noire 600 ml',
                'slug' => 'secret-bath-gold-dream-gel-de-bain-tulipan-negro-noire-600-ml',
                'short_description' => 'Secret Bath Gold Dream Gel de bain tulipan Negro noire 600 ml',
                'description' => 'Secret Bath Gold Dream Gel de bain tulipan Negro noire 600 ml',
                'regular_price' => 32.0,
                'sale_price' => null,
                'SKU' => 'TN-86-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Secret_Bath_Gold_Dream_Gel_de_bain_tulipan_Negro_noire_600_ml_86.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de bain Vanille et Noix de Macadamia 650 ml',
                'slug' => 'gel-de-bain-vanille-et-noix-de-macadamia-650-ml',
                'short_description' => 'Gel de bain Vanille et Noix de Macadamia 650 ml',
                'description' => 'Gel de bain Vanille et Noix de Macadamia 650 ml',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-87-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_bain_Vanille_et_Noix_de_Macadamia_650_ml_87.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de bain au lait Merengada et à la cannelle 650 ML tulipan negro',
                'slug' => 'gel-de-bain-au-lait-merengada-et-la-cannelle-650-ml-tulipan-negro',
                'short_description' => 'Gel de bain au lait Merengada et à la cannelle 650 ML tulipan negro',
                'description' => 'Gel de bain au lait Merengada et à la cannelle 650 ML tulipan negro',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-88-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_bain_au_lait_Merengada_et_à_la_cannelle_650_ML_tulipan_negro_88.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de bain original Tulipan Negro 650 ml',
                'slug' => 'gel-de-bain-original-tulipan-negro-650-ml',
                'short_description' => 'Gel de bain original Tulipan Negro 650 ml',
                'description' => 'Gel de bain original Tulipan Negro 650 ml',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-89-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_bain_original_Tulipan_Negro_650_ml_89.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de bain Tulipan negro Fraise et Cerise 650 ml',
                'slug' => 'gel-de-bain-tulipan-negro-fraise-et-cerise-650-ml',
                'short_description' => 'Gel de bain Tulipan negro Fraise et Cerise 650 ml',
                'description' => 'Gel de bain Tulipan negro Fraise et Cerise 650 ml',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-90-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_bain_Tulipan_negro_Fraise_et_Cerise_650_ml_90.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

            [
                'name' => 'Gel de bain à l’Aloe Vera Tulipan Negro 650 ml',
                'slug' => 'gel-de-bain-l-aloe-vera-tulipan-negro-650-ml',
                'short_description' => 'Gel de bain à l’Aloe Vera Tulipan Negro 650 ml',
                'description' => 'Gel de bain à l’Aloe Vera Tulipan Negro 650 ml',
                'regular_price' => 25.0,
                'sale_price' => null,
                'SKU' => 'TN-91-1759078998',
                'stock_status' => 'outofstock',
                'featured' => false,
                'quantity' => 0,
                'thumbnail' => 'product_images/Gel_de_bain_à_l’Aloe_Vera_Tulipan_Negro_650_ml_91.webp',
                'images' => null,
                'category_id' => 1, // يمكنك تغيير هذا لاحقًا
                'brand_id' => null,
                'status' => 'active',
                'created_at' => '2025-09-28 18:03:18',
                'updated_at' => '2025-09-28 18:03:18',
            ],

        ]);
    }
}
